export const supriseMePrompts=[
   'Avokado şeklinde bir koltuk',
   'Salvador Dalinin dama oynayan bir kediyi betimlediği sürrealist, rüya gibi bir yağlı boya tablosu',
   'oyuncak ayılar Japonyada market alışverişi yapıyor, ukiyo-e',
   "Matisse tarafından satranç oynayan insansı bir robotun yağlı boya tablosu",
   'köpüklü kimyasalları ve dijital sanatı karıştıran deli bilim adamı panda',
   "Hawaii'de iki farenin makro 35mm fotoğrafı, her biri minicik mayolar giyiyor ve minicik sörf tahtaları taşıyorlar, dijital sanat",
   'Koyu mavi arka planda bir akvaryumdaki sevimli bir tropikal balığın 3 boyutlu görüntüsü, dijital sanat',
   'uzayda tropikal bir tatil beldesinde uzanmış bir astronot, vaporwave',
   'Ortaçağ kraliyet cübbesi giyen ve karanlık bir arka plan üzerinde süslü bir taç giyen bir kapibaranın yağlı boya tablosu',
   'bir hamburger ve patates kızartmasını tasvir eden vitray bir pencere',
   'Uçan arabalarla geleceğin parlak bir kentinin karakalem ve sulu boya çizimi',
   'temiz su ile bir havuz ve yarı saydam pastel pembe su ile başka bir havuz ile güneş ışığı alan bir kapalı salon alanı, büyük bir pencerenin yanında, dijital sanat',
   'bir falcı shiba inu kaderini dev bir hamburgerde okuyor, dijital sanat',
   'Johannes Vermeerin inci küpeli su samuru',
   'uzay gemisinde sinirli bir kedinin yağlı pastel çizimi',
   'Yıldızlı Gece tarzında bir tilki resmi',
   "Yünden örülmüş, canavara benzeyen bir tas çorba",
   'Sarı bir duvara oturan peluş oyuncak robot',
   'Denizin yansıtan sularının üzerinde bir sentez dalgası tarzı gün batımı, dijital sanat',
   'Gür yeşilliklerle kaplı bir hava köprüsüne sahip iki fütüristik kule, dijital sanat',
   'Yansıtıcı bir gölün üzerinde uçan gökkuşağı renkli bir sıcak hava balonunun 3 boyutlu görüntüsü',
   "Kulaklık takan bir süper kahramanın çizgi roman kapağı",
   'Siyah bir arka plan üzerinde renkli bir tozun ortalanmış patlaması',
   'Beyaz bir Siyam kedisini kucaklayan dilini çıkarmış bir Samoyed köpeğinin fotoğrafı',
   'Mor bir odada duran beyaz kürklü bir canavarın fotoğrafı',
   "Michelangelo'nun kulaklıkla dj yapan Davut heykelinin bir fotoğrafı",
   'Marsta Ata Binen Bir Samuray, lomography.',
   "Modern, şık bir Cadillac, arka planda bir mercek parlaması, 50 mm fotoğraf ile Toronto şehir merkezi ile Gardiner otobanında ilerliyor",
   'Mavi gözlü ve sarı saçlı genç bir kadının gerçekçi bir fotoğrafı',
   "Başka bir boyuta açılan bir yıldız geçidinin önünde duran bir adam",
   "Blair Cadısı Projesinde Sünger Bob Kare Pantolon",
   'Sosisli sandviç standında çalışan bir velociraptor, lomography',
   "Geceleri Kowloon'un hareketli sokaklarında yürüyen, birçok parlak neon mağaza tabelasıyla aydınlatılan, 50 mm lensli bir adam",
   "Pixar animasyon filmi tarzında canlı bir barbekü",
   "Fütürist bir cyborg dans kulübü, neon ışıklar",
   "Uzun süredir kayıp olan Star Wars 1990 Japon Animesi",
   'Rubik küpü şeklinde bir hamburger, profesyonel yemek fotoğrafçılığı',
   "Bir Synthwave Kirpi, Blade Runner Cyberpunk",
   'Uzak bir gezegende uzaylı bir yaşam formuyla karşılaşan bir astronot, fotoğrafçılık',
   "Cape Town'ı Keşfeden Bir Dinozor, Fotoğraf",
   'Bilgisayarına Aşık Olan Bir Adam, dijital sanat',
   'Geceleri Tokyoyu keşfeden bir cyborg fotoğrafı, lomography',
   '1920lerde New York City caddesinde yürüyen Dracula, siyah beyaz fotoğraf',
   "Synthwave uçağı",
   "Bir adam Tokyo'nun yağmurlu sokaklarında parlak neon tabelalarla dolaşıyor, 50 mm",
   'Cape Town üzerinde uçan bir Uzay Mekiği, dijital sanat',
];